config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  resources :courses do
    collection do
      get 'search'
    end
    resources :reviews, except: [:show, :index]
  end

  get 'pages/about'

  get 'pages/career'

  get 'pages/press'

  get 'pages/tos'

  get 'pages/content'

  get 'pages/privacy'

  get 'pages/contact'

  root 'courses#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/course.rb
class Course < ApplicationRecord
  has_many :reviews
  belongs_to :user, optional: true

  searchkick

  validates :code, :name, :department, presence: true


  def avg_rating
    @reviews = Review.where(course_id: self.id)
    if @reviews.blank?
      0
    else
      @reviews.average(:rating).round(1)
    end
  end
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :course

  validates :title, :tutor, :credit, :mandatory, :online, :review, :rating, presence: true
  validates :rating, numericality: {
    only_integer: true,
    greater_than_or_equal_to: 1,
    less_than_or_equal_to: 10,
    message: "can only be a whole number between 1 and 10"
  }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates_format_of :email, with: /\@mail.ccsf\.edu/, message: ': You can only use a student email address from CCSF'
  validates :first_name, :last_name, presence: true 

  has_many :reviews, dependent: :destroy
  has_many :courses
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name]) 
  end
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :set_course, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:search, :index, :show]
  before_action :check_user, except: [:search, :create, :new, :index, :show]

  def search
    if params[:search].present?
      @courses = Course.search(params[:search])
    else
      @courses = Course.all
    end
  end

  # GET /courses
  # GET /courses.json
  def index
    @courses = Course.all
  end

  # GET /courses/1
  # GET /courses/1.json
  def show
    @reviews = Review.where(course_id: @course.id).order("created_at DESC")
    if @reviews.blank?
      @avg_rating = 0
    else
      @avg_rating = @reviews.average(:rating).round(2)
    end
  end

  # GET /courses/new
  def new
    @course = Course.new
  end

  # GET /courses/1/edit
  def edit
  end

  # POST /courses
  # POST /courses.json
  def create
    @course = Course.new(course_params)
    @course.user_id = current_user.id

    respond_to do |format|
      if @course.save
        format.html { redirect_to @course, notice: 'Course was successfully created.' }
        format.json { render :show, status: :created, location: @course }
      else
        format.html { render :new }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /courses/1
  # PATCH/PUT /courses/1.json
  def update
    respond_to do |format|
      if @course.update(course_params)
        format.html { redirect_to @course, notice: 'Course was successfully updated.' }
        format.json { render :show, status: :ok, location: @course }
      else
        format.html { render :edit }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /courses/1
  # DELETE /courses/1.json
  def destroy
    @course.destroy
    respond_to do |format|
      format.html { redirect_to courses_url, notice: 'Course was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_course
      @course = Course.find(params[:id])
    end

    def check_user
      unless (@course.user == current_user)
        redirect_to root_url, alert: "Sorry, only the original course author can do that!"
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def course_params
      params.require(:course).permit(:code, :name, :department)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end

  def career
  end

  def press
  end

  def tos
  end

  def content
  end

  def privacy
  end

  def contact
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_review, only: [:edit, :update, :destroy]
  before_action :set_course
  before_action :check_user, only: [:edit, :update, :destroy]

  # GET /reviews
  # GET /reviews.json

  # GET /reviews/new
  def new
    @review = Review.new
  end

  # GET /reviews/1/edit
  def edit
  end

  # POST /reviews
  # POST /reviews.json
  def create
    puts params
    @review = Review.new(review_params)
    @review.user_id = current_user.id
    @review.course_id = @course.id

    respond_to do |format|
      if @review.save
        format.html { redirect_to @course, notice: 'Review was successfully created.' }
        format.json { render :show, status: :created, location: @review }
      else
        format.html { render :new }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reviews/1
  # PATCH/PUT /reviews/1.json
  def update
    respond_to do |format|
      if @review.update(review_params)
        format.html { redirect_to course_path(@course), notice: 'Review was successfully updated.' }
        format.json { render :show, status: :ok, location: @review }
      else
        format.html { render :edit }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reviews/1
  # DELETE /reviews/1.json
  def destroy
    @review.destroy
    respond_to do |format|
      format.html { redirect_to course_path(@course), notice: 'Review was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_review
      @review = Review.find(params[:id])
    end

    def set_course
      @course = Course.find(params[:course_id])
    end

    def check_user
      unless (@review.user == current_user)
        redirect_to root_url, alert: "Sorry, only the original author can alter this review"
      end
    end
    # Never trust parameters from the scary internet, only allow the white list through.
    def review_params
      params.require(:review).permit(:tutor, :semester, :year, :title, :credit, :mandatory, :online, :review, :reading1, :reading2, :reading3, :reading4, :rating)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    return '' if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    sentence = I18n.t('errors.messages.not_saved', count: resource.errors.count,
      resource: resource.class.model_name.human.downcase)

    html = <<-HTML
    <div class="alert alert-danger alert-dismissable">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span>
        <span class="sr-only">Close</span>
      </button>
      <h4>#{sentence}</h4>
      #{messages}
    </div>
    HTML

    html.html_safe
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/courses/_form.html.erb
<div class="container">
  <div class="jumbotron">
    <div class="row">
      <div class="col-md-7">
        <h2 style="border-bottom: 1px solid gray; margin-top: 0; padding-bottom: 15px; font-weight: bold; color:#1d7312;"><%= edit ? "Edit" : "Post" %> a course</h2>
        <h3>From<span style="color:#801714"> City College of San Francisco</span></h3><br />
          <%= form_with(model: course, local: true) do |form| %>
            <% if course.errors.any? %>
              <div id="error_explanation" class="alert alert-danger" role="alert">
                <h2><%= pluralize(course.errors.count, "error") %> prohibited this course from being saved:</h2>

                <ul>
                <% course.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
                <% end %>
                </ul>
              </div>
            <% end %>

            <div class="form-group">
              <%= form.text_field :code, id: :course_code, class: "form-control", :placeholder => "Course Code. Ex. CS177", :maxlength => 8 %>
            </div><br />

            <div class="form-group">
              <%= form.text_field :name, id: :course_name, class: "form-control", :placeholder => "Course Name. Ex. Software Engineering", :maxlength => 32 %>
            </div><br />

            <div class="form-group">
              <%= form.text_field :department, id: :course_department, class: "form-control", :placeholder => "Department Name. Ex. Computer Science", :maxlength => 32 %>
            </div><br />
          </div>

    <div class="col-md-5">
        <h2>Dos</h2>
          <h5>Make sure the course code is correct</h5>
          <h5>Make sure the course name is correct</h5>
          <h5>Make sure the department name is correct</h5>

        <h2>Don'ts</h2>
          <h5>Use profanity, name calling, derogatory terms</h5>
          <h5>Post a course you never took</h5>
        </div>
    </div>
    <div class="form-group">
      <%= form.submit class: "btn btn-lg btn-warning", value: "Submit" %>
      &nbsp;&nbsp;&nbsp;
      <%= link_to 'Cancel', courses_path(@course), class: "btn btn-lg btn-default" %>
    </div>
  <% end %>
  </div>
</div>

app/views/courses/edit.html.erb
<%= render 'form', course: @course, edit: true %>

app/views/courses/index.html.erb
<div class="container">
  <div class ="jumbotron" style="padding-top: 80px;">
    <div class="row">
      <div class="col-xs-6">
        <h1 style="font-size: 37px; margin: 0">I want to rate my course for</h1>
      </div>
      <%= form_tag search_courses_path, method: :get, class: "navbar-form navbar-left" do %>
      <div class="col-xs-6">
        <%= text_field_tag :search, params[:search], class: "form-control", placeholder: "Department Name / Course Code", style: "font-size: 18px", :size=>"40" %>
      </div>
    </div>

    <div style="text-align: center; margin-top: 60px;">
      <%= submit_tag "Search", name: nil, class: "btn btn-primary btn-lg" %>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
      <% if user_signed_in? %>
        <%= link_to 'Post Course', new_course_path, class: "btn btn-warning btn-lg" %>
      <% end %>
    </div>
    <% end %>
  </div>

  <h2 class="bar"><span style="text-align: center; font-size: 26px;">Recent Course</span></h2>

  <% @courses.each do |course| %>
  <div style="margin-top: 25px; background: white; padding: 20px;">
  <div class="row">
    <div class="col-md-4">
      <h3 style="font-size: 2.5em; font-weight: bold;"><%= link_to course.code, course %>
        <% if user_signed_in? && course.user == current_user %>
          <span style="font-size: 15px; "><%= link_to 'Edit', edit_course_path(course) %></span>
          <span style="font-size: 15px; "><%= link_to 'Destroy', course, method: :delete, data: { confirm: 'Are you sure?' } %></span>
        <% end %>
      </h3>

      <p style="color: grey; font-size: 1.2em">
        <strong><%= link_to course.name, course %></strong>
      </p>

      <p style="font-size: 1.2em">
        <%= course.department %> Department
      </p>

      <h3 style="color:#801714"><strong>City College of San Francisco</strong></h3>
      <h4 style="color: #f1a82b">Average Rating : <%= course.avg_rating %> / 10 </h4>
      <div style="margin-top: 30px">
        <%= link_to "Rate This Course", new_course_review_path(course), class: "btn btn-success"%>
      </div>

    </div>

    <div class="col-md-8">
      <% review = course.reviews.order('id DESC').limit(1).first %>
      <% if review == nil %>
        <h3 style="color: gray">No review.<br /><br /> Be the first one to rate this course!</h3>
      <% else %>
        <div style="background-color: white">
          <div class="row">
            <div class="col-md-8">
              <h3><%= review.title %></h3>
              <h5 style="color:#6a8b99">Tutor(s): <%= review.tutor %></h5>
            </div>
            <div class="col-md-4" style="text-align: right">
              <h4 style="color: #f19c1c; padding-top: 15px;"><strong>Rating : <%= review.rating %> out of 10</strong></h4>
            </div>
          </div>
          <div class="row" style="color: grey">
            <div class="col-md-12 course-attrs">
              <span><%= review.semester %>&nbsp;&nbsp;<%= review.year.strftime "%Y" if review.year %></span>
              <span><%= review.credit %></span>
              <span><%= review.mandatory %></span>
              <span><%= review.online %></span>
              <span><a style="cursor:pointer" onclick="open_reading('<%= review.reading1 %>','<%= review.reading2 %>','<%= review.reading3 %>','<%= review.reading4 %>'); ">Reading Materials</a></span>
            </div>
          </div>
          <hr>
          <p style="font-size: 1.5em; line-height: 30px"><%= h(review.review).gsub(/\n/, '<br/>').html_safe %></p>
          <hr>
          <div class="row">
            <div class="col-md-8">
              <p style="color: gray">Posted by : <%= "#{review.user.first_name.capitalize} #{review.user.last_name.capitalize[0]}." %><br />
              Created at : <%= review.created_at.strftime("%B %d, %Y") %></p>
            </div>
            <div class="col-md-4" style="text-align: right">
              <% if user_signed_in? %>
                <% if (review.user == current_user) %>
                  <p><%= link_to "Edit", edit_course_review_path(course, review) %> |
                  <%= link_to "Delete", course_review_path(course, review), method: :delete %></p>
                <% end %>
              <% end %>
            </div>
          </div>
        </div>
      <% end %>
      </div>
    </div>
  </div>
    <% end %>
  </div>
</div>

app/views/courses/new.html.erb
<%= render 'form', course: @course, edit: false %>

app/views/courses/search.html.erb
<div class="container">
  <h2 class="bar"><span style="text-align: center; font-size: 26px;">Search Result</span></h2>
  <div style="padding: 0px;">
  <% if @courses.length == 0 %>
    <div style="background-color: white; margin: 20px 0 0 0; padding: 20px 25px; font-size: 1.5em">
      The course you are looking for has not been posted yet. Be the first one to
      <% if user_signed_in? %>
        <%= link_to 'post it', new_course_path, class: "btn btn-warning" %>
      <% end %>
    </div>
  <% end %>

  <% @courses.each do |course| %>
  <div style="margin-top: 25px; background: white; padding: 20px;">
    <div class="row">
    <div class="col-md-4">
      <h3 style="font-size: 2.5em; font-weight: bold;"><%= link_to course.code, course %>
        <% if user_signed_in? && course.user == current_user %>
          <span style="font-size: 15px; "><%= link_to 'Edit', edit_course_path(course) %></span>
          <span style="font-size: 15px; "><%= link_to 'Destroy', course, method: :delete, data: { confirm: 'Are you sure?' } %></span>
        <% end %>
      </h3>

      <p style="color: grey; font-size: 1.2em">
        <strong><%= link_to course.name, course %></strong>
      </p>

      <p style="font-size: 1.2em">
        <%= course.department %> Department
      </p>

      <h3 style="color:#801714"><strong>City College of San Francisco</strong></h3>
      <h4 style="color: #f1a82b">Average Rating : <%= course.avg_rating %> / 10 </h4>
      <div style="margin-top: 30px">
        <%= link_to "Rate This Course", new_course_review_path(course), class: "btn btn-success"%>
      </div>
    </div>
  </div>
  </div>
  <% end %>
</div>
</div>

app/views/courses/show.html.erb
<script>
function open_reading(url1, url2, url3, url4) {
  if (url1) {
    window.open(url1, '_blank');
  }
  if (url2) {
    window.open(url2, '_blank');
  }
  if (url3) {
    window.open(url3, '_blank');
  }
  if (url4) {
    window.open(url4, '_blank');
  }
}
</script>

<div class="container">
  <div class="jumbotron" style="position: relative;">
    <div class="row">
      <div class="col-md-7">
        <p style="font-size: 2.5em; font-weight: bold;"><%= @course.code %>
        <span style="font-size: 15px; "><%= link_to 'Edit', edit_course_path(@course) %></span>
        <span style="font-size: 15px; "><%= link_to 'Destroy', @course, method: :delete, data: { confirm: 'Are you sure?' } %></span></p>

        <p style="color: grey; font-size: 25px;">
          <strong><%= @course.name %></strong>
        </p>

        <p>
          <%= @course.department %> Department
        </p>

        <h3 style="color:#801714"><strong>City College of San Francisco</strong></h3>
        <h4 style="color: #f1a82b">Rating : <%= @course.avg_rating %> out of 10 <%= "( total #{@reviews.length} reviews )" %></h4>

      </div>
      <div class="col-md-5" style="position: absolute; bottom: 30px; right:20px;">
      <%= link_to "Rate This Course", new_course_review_path(@course), class: "btn btn-success btn-lg pull-right active"%>
      </div>

    </div>
  </div>
</div>

<div class="container">
    <% if @reviews.blank? %>
      <h3 style="background-color: white; margin: 20px 0 0 0; padding: 20px 25px;">No reviews yet. Be the first to write one!</h3>
    <% else %>
      <h2 class="bar"><span style="text-align: center; font-size: 26px;">Recent Reviews</span></h2>
      <% @reviews.each do |review| %>
        <div style="background-color: white; margin: 20px 0 0 0; padding: 20px 25px;">
          <div class="row">
            <div class="col-md-8">
              <h3><%= review.title %></h3>
              <h5 style="color:#6a8b99">Tutor(s): <%= review.tutor %></h5>

            </div>
            <div class="col-md-4" style="text-align: right">
              <h4 style="color: #f1a82b; padding-top: 15px;"><strong>Rating : <%= review.rating %> out of 10</strong></h4>
            </div>
          </div>
          <div class="row" style="color: grey">
            <div class="col-md-12 course-attrs">
              <span><%= review.semester %>&nbsp;&nbsp;<%= review.year.strftime "%Y" if review.year %></span>
              <span><%= review.credit %></span>
              <span><%= review.mandatory %></span>
              <span><%= review.online %></span>
              <span><a style="cursor:pointer" onclick="open_reading('<%= review.reading1 %>','<%= review.reading2 %>','<%= review.reading3 %>','<%= review.reading4 %>'); ">Reading Materials</a></span>
            </div>
          </div>
          <hr>
          <p style="font-size: 1.5em; line-height: 30px"><%= h(review.review).gsub(/\n/, '<br/>').html_safe %></p>
          <hr>
          <div class="row">
            <div class="col-md-8">
              <p style="color: gray">Posted by : <%= "#{review.user.first_name.capitalize} #{review.user.last_name.capitalize[0]}." %><br />
              Created at : <%= review.created_at.strftime("%B %d, %Y") %></p>
            </div>
            <div class="col-md-4" style="text-align: right">
              <% if user_signed_in? %>
                <% if (review.user == current_user) %>
                  <p><%= link_to "Edit", edit_course_review_path(@course, review) %> |
                  <%= link_to "Delete", course_review_path(@course, review), method: :delete %></p>
                <% end %>
              <% end %>
            </div>
          </div>
        </div>
      <% end %>
    <% end %>
</div>

app/views/layouts/_bootstrap.html.erb
<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

<!-- Latest compiled and minified JQuery -->
<script
  src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
  integrity="sha256-k2WSCIexGzOj3Euiig+TlR8gA0EmPjuc79OEeY5L45g="
  crossorigin="anonymous"></script>

app/views/layouts/_footer.html.erb
<div class="container" style="margin-top: 20px">
  <nav class="navbar navbar-default" role="navigation">
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "About Us", pages_about_path %></li>
        <li><%= link_to "Career", pages_career_path %></li>
        <li><%= link_to "Content Guidelines", pages_content_path %></li>
        <li><%= link_to "Contact Us", pages_contact_path %></li>
      </ul>
    </div><!-- /.navbar-collapse -->
    <div style="padding: 5px 25px">
      <p>&copy; Rate My Course</p>
    </div>
  </nav>
</div><!-- /.container -->

app/views/layouts/_navbar.html.erb
<div class="container">
  <nav class="navbar navbar-default logo" role="navigation">
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <a class="homelink" href="<%= root_path %>"></a>
      <div class="navcontent">
        <ul class="nav navbar-nav navbar-right" style="font-size:15px">
          <% if user_signed_in? %>
            <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
            <li><%= link_to "Sign out", destroy_user_session_path, method: :delete %></li>
          <% else %>
            <li><%= link_to "Log in", new_user_session_path %></li>
            <li><%= link_to "Sign up", new_user_registration_path %></li>
          <% end %>
        </ul>
      </div>
    </div><!-- /.navbar-collapse -->
  </nav>
</div><!-- /.container -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rate My Course</title>
    <%= csrf_meta_tags %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/bootstrap' %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link href='https://fonts.googleapis.com/css?family=Chivo' rel='stylesheet' type='text/css'>

  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <div class="container">
      <% flash.each do |name, msg| %>
      <% if msg.is_a?(String) %>
        <div class="alert alert-<%= name == "notice" ? "success" : "danger" %> alert-dismissable">
          <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
          <%= content_tag :div, msg, :id => "flash_#{name}" %>
        </div>
      <% end %>
    <% end %>
    </div>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/pages/about.html.erb
<div class="container">
  <div style="background-color: white; line-height: 30px; margin: 20px 0 0 0; padding: 20px 25px; font-size: 1.5em;">
    <h3>About Rate My Course</h3><hr>
    Rate My Course is developed and designed by Maya Novarini, as part of her final project for
    Software Engineering course by Aaron Brick.
    <br /><br />
    Technology stack used was Ruby on Rails, Javascript and Bootstrap... and tons of gems.
    Built upon Rails 5 and Ruby 2.3.4
    <br /><br />
    Visit developer's website <a href="http://www.mayanovarini.com" target="_blank">here </a>

  </div>
</div>

app/views/pages/career.html.erb
<div class="container">
  <div style="background-color: white; line-height: 30px; margin: 20px 0 0 0; padding: 20px 25px; font-size: 1.5em;">
    <h3>Career</h3><hr>
    No jobs but let's meet and see if we can work on something together!
    <br /><br />
    I mainly work with Ruby, Rails and Javascript.
    <br /><br />
    Visit developer's website <a href="http://www.mayanovarini.com" target="_blank">here </a>

  </div>
</div>

app/views/reviews/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Reviews</h1>

<table>
  <thead>
    <tr>
      <th>Tutor</th>
      <th>Semester</th>
      <th>Year</th>
      <th>Title</th>
      <th>Credit</th>
      <th>Mandatory</th>
      <th>Online</th>
      <th>Review</th>
      <th>Reading1</th>
      <th>Reading2</th>
      <th>Reading3</th>
      <th>Reading4</th>
      <th>Rating</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @reviews.each do |review| %>
      <tr>
        <td><%= review.tutor %></td>
        <td><%= review.semester %></td>
        <td><%= review.year %></td>
        <td><%= review.title %></td>
        <td><%= review.credit %></td>
        <td><%= review.mandatory %></td>
        <td><%= review.online %></td>
        <td><%= review.review %></td>
        <td><%= review.reading1 %></td>
        <td><%= review.reading2 %></td>
        <td><%= review.reading3 %></td>
        <td><%= review.reading4 %></td>
        <td><%= review.rating %></td>
        <td><%= link_to 'Show', review %></td>
        <td><%= link_to 'Edit', edit_review_path(review) %></td>
        <td><%= link_to 'Destroy', review, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Review', new_review_path %>

app/views/reviews/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Tutor:</strong>
  <%= @review.tutor %>
</p>

<p>
  <strong>Semester:</strong>
  <%= @review.semester %>
</p>

<p>
  <strong>Year:</strong>
  <%= @review.year %>
</p>

<p>
  <strong>Title:</strong>
  <%= @review.title %>
</p>

<p>
  <strong>Credit:</strong>
  <%= @review.credit %>
</p>

<p>
  <strong>Mandatory:</strong>
  <%= @review.mandatory %>
</p>

<p>
  <strong>Online:</strong>
  <%= @review.online %>
</p>

<p>
  <strong>Review:</strong>
  <%= @review.review %>
</p>

<p>
  <strong>Reading1:</strong>
  <%= @review.reading1 %>
</p>

<p>
  <strong>Reading2:</strong>
  <%= @review.reading2 %>
</p>

<p>
  <strong>Reading3:</strong>
  <%= @review.reading3 %>
</p>

<p>
  <strong>Reading4:</strong>
  <%= @review.reading4 %>
</p>

<p>
  <strong>Rating:</strong>
  <%= @review.rating %>
</p>

<%= link_to 'Destroy', review, method: :delete, data: { confirm: 'Are you sure?' } %>
<%= link_to 'Edit', edit_review_path(@review) %> |
<%= link_to 'Back', reviews_path %>